<?php if ($block->getPaymentMethod() === "genpay_billet"): ?>

    <script>
        function copyTextToClipboard(text) {
            var textArea = document.createElement("textarea");
            textArea.style.position = 'fixed';
            textArea.style.top = 0;
            textArea.style.left = 0;
            // Ensure it has a small width and height. Setting to 1px / 1em
            // doesn't work as this gives a negative w/h on some browsers.
            textArea.style.width = '2em';
            textArea.style.height = '2em';
            // We don't need padding, reducing the size if it does flash render.
            textArea.style.padding = 0;
            // Clean up any borders.
            textArea.style.border = 'none';
            textArea.style.outline = 'none';
            textArea.style.boxShadow = 'none';
            // Avoid flash of white box if rendered for any reason.
            textArea.style.background = 'transparent';
            textArea.value = text;
            document.body.appendChild(textArea);
            textArea.select();
            try {
                var successful = document.execCommand('copy');
                var msg = successful ? '*Link copiado com sucesso.' : '*Erro ao copiar link.';
            } catch (err) {
                console.log(msg);
            }
            document.body.removeChild(textArea);
        }
    </script>

    <?php if ($block->getBilletUrl()): ?>
        <?php if ($block->getBilletDisplay() == "tab"): ?>
            <p>
                <a href="<?php echo $block->getBilletUrl(); ?>" target="_blank" class="action primary continue" title="Abrir Boleto em nova Aba">Visualizar Boleto</a>
                <button class="action primary continue" onclick="copyTextToClipboard('<?php echo $block->getBilletUrl(); ?>')">Copiar Link do Boleto</button>
            </p>
        <?php else: ?>
            <p>
                <button class="action primary continue" onclick="window.location.href='<?php echo $block->getBilletUrl(); ?>'">Visualizar Boleto</button>
                <button class="action primary continue" onclick="copyTextToClipboard('<?php echo $block->getBilletUrl(); ?>')">Copiar Link do Boleto</button>
            </p>
        <?php endif;?>
    <?php endif; ?>
<?php endif; ?>