<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                title: $.mage.__('Validate Credential GenPay'),
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Close'),
                    // class: 'mymodal1',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var validateCredential = $('#validate-credential-modal');
            var popup = modal(options, validateCredential);
            $("#validate-credential").on('click',function() {
                $.ajax('<?php echo $block->getAjaxUrl() ?>', {
                    data: {
                        taxvat : function () {
                            return document.querySelector('input[id*=genpay_configuration_document]').value;
                        },
                        apiKey : function () {
                            return document.querySelector('input[id*=genpay_configuration_api_key]').value;
                        },
                        signature : function () {
                            return document.querySelector('input[id*=genpay_configuration_signature]').value;
                        },
                        environment : function () {
                            return document.querySelector('select[id*=genpay_configuration_environment]').value;
                        }
                    },
                    success: function(response) {
                        validateCredential.text(response.message);
                        validateCredential.modal("openModal");
                    },
                    error: function(error) {
                        validateCredential.text("Falha na comunicação.");
                        validateCredential.modal("openModal");
                    }
                });
            });
        }
    );
</script>
<style type="text/css">
    .modal-popup .modal-inner-wrap{ width: 50%; }
</style>
<?php echo $block->getButtonHtml() ?>
<div id="validate-credential-modal" ></div>

